### ISSUE TITLE
Cannot install the application due to invalid certificate

### ISSUE THREAD

**Issue by Soniyck** [iguana-technology/Iguana.AwsParameterStoreApp#1]
When trying to install the 1.1.0.0 version, windows shows an error

```
Certifikát vydavatele tohoto balíčku aplikace se nepovedlo ověřit. Požádejte správce systému nebo vývojáře aplikace o nový balíček aplikace s ověřenými certifikáty. Kořenový certifikát a všechny okamžité certifikáty podpisu v balíčku aplikace se musí ověřit (0x800B010A).
```

![image](https://user-images.githubusercontent.com/16019696/229544708-a8e3c5d8-3449-4535-8b64-b5db214f0b42.png)

Tried importing the included cert manually, which did not resolve the issue.

**Comment by magiak** [comment]
Hi thank you for reporting the issue. The application is signed by self signed certificate and the certificate has to be installed manually. Here is official link to the documentation https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-7.0#installing-the-app

**Comment by Soniyck** [comment]
Thank you, this worked.
